apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: suu-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
